#!/bin/bash
g++ -c main.cpp
g++ -c main.cpp -I /home/alicezed/Рабочий\ стол/std/Project\ SFML/SFML/include
g++ main.o -o sfml-app -lsfml-graphics -lsfml-window -lsfml-system
g++ main.o -o sfml-app -L /home/alicezed/Рабочий\ стол/std/Project\ SFML/SFML/lib -lsfml-graphics -lsfml-window -lsfml-system
export LD_LIBRARY_PATH=/home/alicezed/Рабочий\ стол/std/Project\ SFML/SFML/lib && ./sfml-app

